ijot1/site/__init__.py
from flask import Blueprint

sitemod = Blueprint('site', __name__, template_folder='templates')

from . import views

ijot1/site/views.py
from flask import render_template, url_for, request,g,redirect,flash,session
from ijot1 import db,ma
from ijot1.models import  User,Notes,note_schema
from functools import wraps
from . import sitemod
import os


"""@sitemod.before_request
def before_request():
	g.user = None
	if 'user' in session:
		g.user = session['user']"""

def login_required(f):
	@wraps(f)
	def function(*args,**kwargs):
		g.user = None
		if 'user' in session:
			g.user = session['user']
			current_user = g.user
			return f(current_user,*args,**kwargs)
		else:
			session['error'] = "Log in to access this service"
			return redirect(url_for('site.signin'))
	return function

@sitemod.route('/')
@sitemod.route('/index')
def index():
	return render_template('index.html')

@sitemod.route('/signup',methods=['GET','POST'])
def signup():
	if request.method == 'POST':
		# fetch data 
		name = request.form['name']
		email = request.form['email']
		password = request.form['password']

		new_user = User(name=name,email=email,password=password)

		db.session.add(new_user)
		db.session.commit()
	return render_template('signup.html')

# user login
@sitemod.route('/signin',methods=['GET','POST'])
def signin():
	if request.method == 'POST':
		email = request.form['email']
		user = User.query.filter_by(email=email).first()
		if user != None:
			password = user.password
			if request.form['password'] == password:
				session['user'] = request.form['email']
				username = user.name
				return redirect(url_for('site.dashboard'))
			else:
				error='Password incorrect - forgot password?'
				return render_template('signup.html')
		else:
			error = 'No user with that email was found'
			return render_template('signup.html',error=error)
	if session['error']:
		return render_template('signup.html',error=session['error'])
	else:
		return render_template('signup.html'),200

@sitemod.route('/dashboard')
@login_required
def dashboard(current_user):
	if g.user:
		usermail = session['user']
		username = User.query.filter_by(email=usermail).first().name
		user_id = User.query.filter_by(email=usermail).first().id
		# check if user has notes
		data = Notes.query.filter_by(user_id=user_id).all()
		if len(data) > 0:
			notes = data
			return render_template('dashboard.html',username=username,notes=notes)
		else:
			error = "You haven't added any note yet"
			return render_template('dashboard.html',username=username,error=error)
	else:
		return redirect(url_for('site.signup'))

@sitemod.route('/note',methods=['GET','POST'])
@login_required
def note(current_user):
	data = request.get_json('id')
	id = int(data['id'])
	note = Notes.query.get(id)
	return redirect(url_for('fullfeat',note=note))
		

@sitemod.route('/logout')
@login_required
def logout(current_user):
	session.pop(current_user,None)
	
	return redirect(url_for('site.signup'))

@sitemod.route('/new_note',methods=['GET','POST'])
@login_required
def new_note(current_user):
	if request.method == 'POST':
		if g.user:
			title = request.form['note-title']
			body = request.form['note-body']
			user_id = User.query.filter_by(email=g.user).first().id
			note = Notes(title=title,body=body,user_id=user_id)
			
			# fetch the note for display
			db.session.add(note)
			db.session.commit()


	return redirect(url_for('site.dashboard'))

@sitemod.route('/get_note/<id>',methods=['GET','POST'])
@login_required
def get_note(current_user,id):
	note = Notes.query.get(id)
	return render_template('notepage.html')

ijot1/site/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{url_for('static',filename='styles/dashboard.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
    <title></title>
</head>

<body>
    <div class="container" id="container">
        <div class="header">
            <h2>Welcome {{username}}</h2>
        </div>
        <div class="nav">
            <input type="text" placeholder=" Look up note" size="10px">
            <a href="{{ url_for('site.logout') }}"><button id="logout-btn">Logout</button></a>
        </div>
        <div class="menu">
            <button>Add a note</button>
            <button>Delete note</button>
        </div>
        <div class="showcase">
            <button id="add-btn">
                <h1>+</h1> 
            </button>
            <div class="notes" id="notes">
                {% if notes %}
                    {% for i in notes %}
                        <button class="note-container" id="{{i.id}}" onclick="getNotes(event)"> {{ i.body }}</button>
                    {% endfor %}
                {% endif %}
                
                {% if error %}
                    <span id="error">{{ error }}</span>
                {% endif %}
            </div>
        </div>
        <div class="add-note-container">
            <form class="note-form" id="note-form" action="new_note" method="POST">
                <input type="text" placeholder="Enter a note title" name="note-title" id="note-title">
                <textarea id="note-body" name="note-body">Enter note body here..</textarea>
                <button type="button" id="next-note-btn">Next</button>
                <button id="submit-note-btn">Submit</button>
            </form>
        </div>
        <div class="share">
            <button></button>
        </div>
    </div>
    <script src="../../static/scripts/dashboard.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</body>
</html>

ijot1/site/templates/includes/_footer.html
<footer>
    <span> Ijot 2019 &copy; Copyright</span>
</footer>

ijot1/site/templates/includes/_navbar.html
<header>
    <nav class="navbar">
        <ul id="nav1">
            <li href="#">Home</li>
            <li href="#">About</li>
            <li href="#">Download</li>
        </ul>
        <ul id="nav2">
            <li>Sign-Up</li>
            <li>Sign-In</li>
        </ul>
    </nav>
</header>

ijot1/site/templates/index.html
{% extends 'layout.html' %}

{% block body %}
	<section id="sec1">
		<div>
			<img src="../../static/img/document.png" alt="">
		</div>
		
		<div id="pdiv">
			<h1>Ijot</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique aperiam provident suscipit neque! Consequuntur soluta ducimus veniam! Commodi, labore dolores exercitationem repellendus ipsa praesentium rem pariatur dolorum veritatis temporibus nesciunt fuga eaque debitis consequuntur, nemo suscipit eum officiis natus? Pariatur delectus provident quos natus incidunt odio corrupti quas libero non. Sapiente cumque ipsum nisi iste praesentium. Voluptatibus dignissimos praesentium ut, tempore consequatur beatae delectus suscipit enim veritatis, magnam at quos consequuntur molestias laborum, saepe adipisci numquam blanditiis deleniti. Sed odit quia voluptatem corrupti reprehenderit, repudiandae nulla aspernatur aliquam facilis quidem ex obcaecati a possimus nemo animi adipisci, quibusdam, quam quisquam.</p>
			<br>
			<a href="{{url_for('site.signup')}}" id="mnote"><button>Make a Note now</button></a>
		</div>
	</section>

{% endblock %}

ijot1/site/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/index.css') }}">
    <title></title>
</head>
<body>
    {% include 'includes/_navbar.html' %}
    {% block body %}{% endblock %}
    {% include 'includes/_footer.html' %}

</body>
</html>

ijot1/site/templates/note.html
<!DOCTYPE html>
<html>
<head>
	<title>Ijot | Index</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/note.css') }}">
</head>
<body>
	<p>
		{{note}}
	</p>
</body>
</html>

ijot1/site/templates/notepage.html
<!DOCTYPE html>
<html>
<head>
	<title>Ijot | Index</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/index.css') }}">
</head>
<body>

</body>
</html>

ijot1/site/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('static',filename='styles/signup.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
</head>
<body>
    <div class="error">
        {{error}}
    </div>
    <div class="container" id="container">
        <div class="form-container sign-up-container">
            <form action="signup" method='POST'>
                <h1>Create Account</h1>
                <div class="social-container">
                    <a href="" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                <input type="text" name="name" placeholder="Name">
                <input type="email" name="email" placeholder="Email">
                <input type="password" name="password" placeholder="Password">
                <button type='submit'>Sign Up</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form action="signin" method="POST">
                <h1>Sign In</h1>
                <div class="social-container">
                    <a href="" class="social"><i class="fab fa-facebook-f"></i></a>
                    <a href="" class="social"><i class="fab fa-google-plus-g"></i></a>
                    <a href="" class="social"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <span>Or use your account</span>
                <input type="text" name="email" placeholder="Email">
                <input type="text" name="password" placeholder="Password">
                <span>Forgot your password?</span>
                <button type='submit'>Sign In</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>
                        To continue documenting your thoughts, please login with your personal details
                    </p>
                    <button class="ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Hello friend!</h1>
                    <p>Enter your personal details and start your journey with us</p>
                    <button class="ghost" id="signUp">Sign Up</button>
                </div>
            </div>
        </div>
    </div>
    <script src="../../static/scripts/signup.js"></script>
</body>
</html>